
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

const dbUrl = process.env.DATABASE_URL && !process.env.DATABASE_URL.includes("host:5432") && !process.env.DATABASE_URL.includes("placeholder")
  ? process.env.DATABASE_URL
  : `file:${path.resolve(process.cwd(), "prisma/dev.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: dbUrl,
  },
});
