
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const FALLBACK_DATABASE_URL = "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` does not need a live database connection, but Vercel's
    // install step may run before preview env vars are available.
    url: process.env.DATABASE_URL || FALLBACK_DATABASE_URL,
  },
});
